version: '3.9'

services:

  backend:
    build: ./backend
    container_name: backend_container
    restart: unless-stopped
    expose:
      - "5000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    container_name: frontend_container
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    restart: unless-stopped